EdDSA:
  type: Article
  title: High-speed high-security signatures
  author: [Daniel J. Bernstein, Niels Duif, Tanja Lange, Peter Schwabe, Bo-Yin Yang]
  date: 2011-09-26
  url: https://ed25519.cr.yp.to/ed25519-20110926.pdf

DH:
  type: Article
  title: New directions in cryptography
  author: [W. Diffie, M. E Hellman] 
  date: 1976
  url: https://ee.stanford.edu/~hellman/publications/24.pdf

RSA:
  type: Article
  title: A method for obtaining digital signatures and public-key cryptosystems
  author: [R. L. Rivest, A. Shamir, L. Adleman]
  date: 1985
  url: https://people.csail.mit.edu/rivest/Rsapaper.pdf

ElGamal:
  type: Article
  title:  Public Key Cryptosystem and a Signature Scheme Based on Discrete Logarithms
  author: TAHER ELGAMAL
  url: https://caislab.kaist.ac.kr/lecture/2010/spring/cs548/basic/B02.pdf

GNFS:
  type: Article
  title: The development of the number field sieve
  author: [Arjen K. Lenstra, H. W. Lenstra]
  
KeySizeRec:
  type: Article
  title: "Recommendation for key management. Part 3: Application-specific key management guidance"
  author: [E. Barker, Q.Dang]
  url: http://dx.doi.org/10.6028/NIST.SP.800-57pt3r1

BonehShoup:
  type: Book
  title: A Graduate Course in Applied Cryptography
  author: [Dan Boneh, Victor Shoup]
  date: 2023
  url: http://toc.cryptobook.us/book.pdf 

MathCrypto:
  type: Book
  title: An Introduction to Mathimatical Cryptography
  author: [Jeffrey Hoffstein, Jill Pipher, Joseph H. Silverman]
  date: 2014

Schoof:
  type: Article
  title: Elliptic curves over finite fields and the computation of square roots mod p
  author: R. Schoof. 
  date: 1985

SEA:
  type: Article
  title: Counting Points on Elliptic Curves over Finite Fields
  author: R. Schoof. 
  date: 1995

ECNTC:
  type: Book
  title: "Elliptic Curves: Number Theory and Cryptography"
  author: Lawrence C. Washington
  date: 2008

MontLadder:
  type: Article
  title: Montgomery curves and the Montgomery ladder
  author: [Daniel J. Bernstein, Tanja Lange]
  url: https://eprint.iacr.org/2017/293.pdf

KeyCmpImg:
  type: Site
  title: What is ECC and why would I want to use it?
  url: https://www.globalsign.com/en/blog/elliptic-curve-cryptography